language: node_js
node_js:
  - "4.2"
  - "5.5"
cache:
  directories:
    - node_modules
git:
  depth: 3

after_success:
  - ./node_modules/.bin/istanbul cover --report lcovonly ./node_modules/.bin/_mocha && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js