language: node_js
node_js:
  - "4.2"
  - "5.5"
cache:
  directories:
    - node_modules
git:
  depth: 3

after_success:
  - ./node_modules/.bin/babel-istanbul cover ./node_modules/.bin/_mocha --compilers ./node_modules/babel-core/register && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
